sudo: required
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- echo $REPO:$TAG
- docker build -t $REPO:$TAG .
- docker run --name $IMAGE -d $REPO:$TAG 
- docker ps -a
- sleep 5
- docker logs $IMAGE
- docker exec $IMAGE pgrep pure-ftpd
after_script:
- docker rm -f $IMAGE
- docker rmi $REPO:$TAG
env:
  global:
  - IMAGE=pure-ftpd
  - REPO=ajoergensen/$IMAGE
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
