#!/usr/bin/with-contenv bash
: ${CIPHER_LIST:="EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"}
: ${PUBLICHOST:="ftp.example.com"}

# build up flags passed to this file on run + env flag for additional flags
# e.g. -e "ADDED_FLAGS=--tls=2"
PURE_FTPD_FLAGS="$ADDED_FLAGS -c 50 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P $PUBLICHOST -p 30000:30009"

# detect if using TLS (from volumed in file) but no flag set, set one
if [ -e /etc/ssl/private/pure-ftpd.pem ] && [[ "$PURE_FTPD_FLAGS" != *"--tls"* ]]
 then
    echo "TLS Enabled"
    PURE_FTPD_FLAGS="$PURE_FTPD_FLAGS --tls=1 "
fi

if [[ "$PURE_FTPD_FLAGS" == *"--tls"* ]]
 then
	PURE_FTPD_FLAGS="$PURE_FTPD_FLAGS -J $CIPHER_LIST"
fi

# let users know what flags we've ended with (useful for debug)
echo "Starting Pure-FTPd:"
echo "  pure-ftpd $PURE_FTPD_FLAGS"

# start pureftpd with requested flags
exec /usr/sbin/pure-ftpd $PURE_FTPD_FLAGS
